[build]
command = "npm install -g @angular/cli && npm install && ng build --configuration=production"
publish = "dist/east-west-trading"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[build]
command = "npm install && npx ng build --configuration=production"
publish = "dist/east-west-trading"
[build]
command = "npm install && npx ng build --configuration=production"
publish = "dist/east-west-trading"
